src/Entity/Creneaux.php
<?php

namespace App\Entity;

use App\Repository\CreneauxRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CreneauxRepository::class)]
class Creneaux
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: "datetime")]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column]
    private ?bool $isAvailable = true;

    #[ORM\ManyToOne(inversedBy: 'creneauxes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'creneauxes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Permis $permis = null;

    #[ORM\ManyToOne(inversedBy: 'creneauxess')]
    private ?User $user_Eleve = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function isIsAvailable(): ?bool
    {
        return $this->isAvailable;
    }

    public function setIsAvailable(bool $isAvailable): static
    {
        $this->isAvailable = $isAvailable;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getPermis(): ?Permis
    {
        return $this->permis;
    }

    public function setPermis(?Permis $permis): static
    {
        $this->permis = $permis;

        return $this;
    }

    public function getUserEleve(): ?User
    {
        return $this->user_Eleve;
    }

    public function setUserEleve(?User $user_Eleve): static
    {
        $this->user_Eleve = $user_Eleve;

        return $this;
    }
}

src/Form/CreneauxType.php
<?php
// src/Form/CreneauxType.php

// src/Form/CreneauxType.php

namespace App\Form;

use App\Entity\Creneaux;
use App\Entity\Permis;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CreneauxType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date', null, [
                'label' => 'Date:',
            
            ])
            ->add('permis', EntityType::class, [
                'class' => Permis::class,
                'label' => 'Type:',
                'choice_label' => 'type',
               
            ])
        
            ->add('user', EntityType::class, [
                'class' => User::class,
                'label' => 'Moniteur:',
                'choice_label' => 'firstname',
                'choices' => $options["moniteur"],
                
               
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Creneaux::class,
            'moniteur' => null,
            // 'eleve' => null,
           
            
        ]);
    }
}

src/Controller/CreneauxController.php
<?php

namespace App\Controller;

use App\Service\Cart;
use App\Entity\Creneaux;
use App\Form\CreneauxType;
use App\Repository\UserRepository;
use App\Repository\CreneauxRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/creneaux')]
class CreneauxController extends AbstractController
{   

    #[Route('/', name: 'app_creneaux_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, UserRepository $userRepository): Response
    {
       //récupération du moniteur et élève 
        $moniteur = $userRepository->getUsersByRole('ROLE_MONITEUR');
        $eleve = $userRepository->getUsersByRole('ROLE_ELEVE');
        // dd($moniteur);
        $creneaux = new Creneaux();
        $form = $this->createForm(CreneauxType::class, $creneaux, ["moniteur" => $moniteur]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($creneaux);
            $entityManager->flush();

            return $this->redirectToRoute('app_creneaux_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('creneaux/new.html.twig', [
            'creneaux' => $creneaux,
            'form' => $form,
        ]);
    }

    #[Route('/list', name: 'app_creneaux_index', methods: ['GET'])]
     public function index(CreneauxRepository $creneauxRepository): Response
     {
         $creneauxes = $creneauxRepository->findAll();
         return $this->render('creneaux/list.html.twig', [
             'creneauxes' => $creneauxes, //
         ]);
     }

    #[Route('/{id}', name: 'app_creneaux_show', methods: ['GET'])]
    public function show(Creneaux $creneaux): Response
    { 
        return $this->render('creneaux/show.html.twig', [
            'creneaux' => $creneaux,
        ]);
    }

    // #[Route('/{id}', name: 'app_creneaux_show', methods: ['GET'])]
    // public function show(Creneaux $creneaux = null): Response
    // {
    //     // Vérifie si l'entité Creneaux existe
    //     if (!$creneaux) {
    //         throw $this->createNotFoundException('Le créneau n\'existe pas.');
    //     }
    
    //     return $this->render('creneaux/show.html.twig', [
    //         'creneaux' => $creneaux,
    //     ]);
    // }

    

    #[Route('/{id}/edit', name: 'app_creneaux_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Creneaux $creneaux, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CreneauxType::class, $creneaux);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_creneaux_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('creneaux/edit.html.twig', [
            'creneaux' => $creneaux,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/delete', name: 'app_creneaux_delete')]
    public function delete(Request $request, Creneaux $creneaux, EntityManagerInterface $entityManager): Response
    {
        if ($creneaux) {
                    $entityManager->remove($creneaux);
                    $entityManager->flush();
                    $this->addFlash('success', 'Votre créneau est supprimé avec succès.');
                }
            return $this->redirectToRoute('app_creneaux_index', [], Response::HTTP_SEE_OTHER);
    
    }
      



    #[Route('/{id}/update', name: 'app_creneaux_update', methods: ['GET', 'POST'])]
    public function update(Request $request, Creneaux $creneaux, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CreneauxType::class, $creneaux);
        $form->handleRequest($request);
    
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();
    
            // Ajoutez une instruction dump pour déboguer
            dump('Redirection effectuée');
    
            return $this->redirectToRoute('app_creneaux_index', [], Response::HTTP_SEE_OTHER);
        }
    
        return $this->render('creneaux/updateCreneaux.html.twig', [
            'creneaux' => $creneaux,
            'form' => $form,
        ]);
    }

   

    #[Route('/creneaux/validate', name: 'app_creneaux_validate', methods: ['GET'])]
    public function validateCreneaux(EntityManagerInterface $entityManager, Cart $cart): Response
    { 
        
        //récupèrent les détails du panier(des creneaux) à partir du service Cart
        $cartCreneaux = $cart->getDetails();
        //stoker les ces détails dans $creneaux
        $creneaux = $cartCreneaux['creneaux'];
        //La boucle itère sur chaque créneau présent dans le panier
        foreach($creneaux as $creneau){
        //stocker Chaque élément de $creneaux 
            // Vérifiez si la plage horaire est disponible
                // Mettez à jour la plage horaire comme réservée
                $creneau->setIsAvailable(false);
        
                // Définissez l'élève qui a réservé la plage horaire 
                $user = $this->getUser(); 
                //  Associe l'élève connecté au créneau
                $creneau->setUserEleve($user);
                // marquer le
                $entityManager->persist($creneau);  
        }
       //Enregistre tous les changements dans la base de données  
        $entityManager->flush();
        //Vide le panier après avoir validé les créneaux
        $cart->remove();
        //Ajoute un message flash de succès
        $this->addFlash('success', 'Vos créneaux sont validés.'); 
         
        // Redirigez vers la page de la liste ou toute autre page appropriée
        return $this->redirectToRoute('app_creneaux_index'); 
    }


    #[Route('/creneaux/{id}/cancel', name: 'app_cancel', methods: ['GET'])]
    public function cancel(Creneaux $creneaux, EntityManagerInterface $entityManager): Response
    {
        //vérifier si l'utilisateur a le role admin (seul autoriser àn annuler)
        if ($this->isGranted('ROLE_ADMIN')) {
            //mettre le creneau dispo
            $creneaux->setIsAvailable(true);
            //sUPPRIMER l'élève en le mettant null
            $creneaux->setUserEleve(null); 
            //mise à jour bdd
            $entityManager->flush();
    
            return $this->redirectToRoute('app_creneaux_index');
        }
    
        $this->addFlash('error', 'Vous n\'êtes pas autorisé à annuler cette réservation.');
    
        return $this->redirectToRoute('app_creneaux_index');
    }
}

templates/creneaux/_delete_form.html.twig
{% if not app.user or 'ROLE_ADMIN' not in app.user.roles %}
    <div class="alert alert-danger" role="alert">
        Vous n'avez pas les droits d'accéder à cette page.
    </div>
{% else %}
<form method="post" action="{{ path('app_creneaux_delete', {'id': creneaux.id}) }}" onsubmit="return confirm('Are you sure you want to delete this creneau?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ creneaux.id) }}">
    <button class="btn">Delete</button>
</form>
{% endif %}

templates/creneaux/_form.html.twig
{% if 'ROLE_ADMIN' not in app.user.roles %}
    <div class="alert alert-danger" role="alert">
        Vous n'avez pas les droits d'accéder à cette page.
    </div>
{% else %}
{# {{ form_start(form) }}
    {{ form_widget(form) }}  
    <button class="btnFormCreneaux">{{ button_label|default('Save') }}</button>
{{ form_end(form) }} #}
{% endif %}

templates/creneaux/edit.html.twig
{# templates/creneaux/edit.html.twig #}
{% extends 'base.html.twig' %}

{% block title %}Edit Creneaux{% endblock %}

{% block body %}
{% if not app.user or 'ROLE_ADMIN' not in app.user.roles %}
        <div class="alert alert-danger" role="alert">
            Vous n'avez pas les droits d'accéder à cette page.
        </div>
{% else %}
        <div class="MinWidthGeneral">
          <div class="creneauH4">
               <h4 id="h4Creneau">Edit Creneaux</h4>
            </div>
           <div class="container">
                <div class="creneauxForm">
                    {{ form_start(form, {'attr': {'class': 'form'}}) }}
                    <div class="form-group">
                        {{ form_label(form.date, 'Date:', {'label_attr': {'class': ''}}) }}
                        {{ form_widget(form.date, {'attr': {'class': 'form-control', 'placeholder': 'Date ...'}}) }}
                    </div>
                    <div class="form-group">
                        <div class="creneauTypeLabel">
                            {{ form_label(form.permis, 'Type:', {'label_attr': {'class': ''}}) }}
                        </div>
                        {{ form_widget(form.permis, {'attr': {'class': 'form-control'}}) }}
                    </div>
                    <div class="form-group">
                        <div class="creneauFirst">
                            {{ form_label(form.user, 'Moniteur:', {'label_attr': {'class': ''}}) }}
                        </div>
                        {{ form_widget(form.user, {'attr': {'class': 'form-control'}}) }}
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-custom">Register</button>
                        {# <a href="{{ path('app_creneaux_index') }}" class="btn btn-secondary"><span>&#128412;</span>List</a> #}
                    </div>
                    {{ form_end(form) }}
                    </div>
                </div>
        </div>
         {% include 'footer.html.twig' %}
    {% endif %}
{% endblock %}

templates/creneaux/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Creneaux index{% endblock %}

{% block body %}
{% if app.flashes('error') %}
    <div class="alert alert-danger" role="alert">
        {% for flash_message in app.flashes('error') %}
            {{ flash_message }}
        {% endfor %}
    </div>
{% elseif app.flashes('success') %}
    <div class="alert alert-success" role="alert">
        {% for flash_message in app.flashes('success') %}
            {{ flash_message }}
        {% endfor %}
    </div>
{% endif %}

{% if not app.user %}
    <div class="alert alert-danger" role="alert">
        Vous n'êtes pas autorisé à accéder à cette page.
    </div>
{% else %}
    <div class="MinWidthGeneral">
        <div class="creneauxGeneral">
            <h2>Creneaux List</h2>
            <div class="table-responsive">
                <table class="table table-striped">
                   <thead>
                        <tr>
                            <th scope="col">Date</th>
                            <th scope="col">Is Available</th>
                            <th scope="col">Moniteur</th>
                            {% if is_granted('ROLE_ELEVE') %}
                            <th scope="col">Elève</th>
                            {% else %}
                                <th>Elèves</th>
                            {% endif %}
                            <th scope="col">Type</th>
                            <th scope="col">Price:€</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody class="table-group-divider">
                    {% for creneau in creneauxes %}
                        {% if creneau.isAvailable or (creneau.userEleve is defined and creneau.userEleve.id is defined and creneau.userEleve.id == app.user.id) or is_granted('ROLE_ADMIN') or is_granted('ROLE_MONITEUR') %}
                        {# 
                        {% if creneau.isAvailable or (creneau.userEleve is defined and attribute(creneau.userEleve, 'id') == app.user.id) or is_granted('ROLE_ADMIN') or is_granted('ROLE_MONITEUR') %}

                         #}
                            <tr>
                                <td>{{ creneau.date ? creneau.date|date('Y-m-d H:i:s') : '' }}</td>
                                <td>{{ creneau.isAvailable ? 'Yes' : 'No' }}</td>
                                <td>{{ creneau.user is not null ? creneau.user.firstname : '' }}</td>
                                
                                {% if is_granted('ROLE_ELEVE') %}
                                    {% if creneau.userEleve.id is defined and creneau.userEleve.id == app.user.id %}
                                        <td>{{ app.user.firstname }}</td>
                                    {% else %}
                                        <td></td>
                                    {% endif %}
                                {% elseif is_granted('ROLE_ADMIN') or is_granted('ROLE_MONITEUR') %}
                                    <td>{{ creneau.userEleve.id is defined ? creneau.userEleve.firstname : '' }}</td>
                                {% else %}
                                    <td></td>
                                {% endif %}
    
                                <td>{{ creneau.permis.type }}</td>
                                <td>{{ creneau.permis.price }}</td>
                                <td>
                                    {% if 'ROLE_ADMIN' in app.user.roles %}
                                        {% if creneau.isAvailable %}
                                            <a class="btn userLien" href="{{ path('app_creneaux_edit', {'id': creneau.id}) }}">Edit</a>
                                            <a class="btn userLien" href="{{ path('app_creneaux_delete', {'id': creneau.id}) }}">Delete</a>
                                        {% elseif not creneau.isAvailable %}
                                            <a class="btn userLienDelet" href="{{ path('app_cancel', {'id': creneau.id}) }}">Annuler</a>
                                        {% endif %}
                                        {# {{ dump(app.session.get('cart')[ creneau.id ])}} #}
                                    {% elseif 'ROLE_ELEVE' in app.user.roles %}
                                        {% if creneau.isAvailable %}
                                            {% if (app.session.get('cart')[ creneau.id ] is not defined) %}
                                                <a  href="{{ path('add_to_cart', {'id': creneau.id}) }}" data-id-creneau = "{{creneau.id}}" class="btn ajax">Réserver</a>
                                                <span id="pris_{{ creneau.id }}" style="display: none;">pris</span>
                                            {% else %}
                                                <span> pris</span>    
                                            {% endif %} 
                                        {% else %}
                                            <span> Réservé</span>    
                                        {% endif %}
                                    {% endif %}
                                </td>
                            </tr>
                        {% endif %}
                    {% else %}
                        <tr>
                            <td colspan="7">No records found</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="crenauxA">          
                {% if app.user and 'ROLE_ADMIN' in app.user.roles %}
                    <a class="btn btn-custom" href="{{ path('app_creneaux_new') }}">Create new</a>
                {% endif %}
            </div>
        </div>
    </div>
{% include 'footer.html.twig' %} 
{% endif %}
{% endblock %}

{% block javascripts %} 


<script>
$(document).ready(function() {
    $("a.ajax").on("click", function(evtClick) {
        evtClick.preventDefault();
        var href = $(this).attr("href");
        var id_creneau = $(this).data("id-creneau");
        //Le lien "Réserver" est masqué  pour éviter que l'utilisateur ne clique plusieurs fois dessus
        $(this).hide();
        $("#pris_" + id_creneau).show();
        $.ajax({
            url: href,
            type:'get',
            //reponse attendue en json
            dataType: "json",
            success: function(response) {
                //La quantité totale de créneaux dans le panier est mise à jour avec la valeur renvoyée par la requête
                $("#nombre").html(response.nb);
                //un message du succès
                //un message du succèsE  
                $("#deja_panier").addClass("alert alert-success").html(response.message);
            },
            error: function(jqXHR, status, error) {
                console.log("ERREUR AJAX", status, error);
            },
        });
    });
});
</script>

{% endblock %}

templates/creneaux/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formulaire Creneaux{% endblock %}

{% block body %}
    {% if not app.user or 'ROLE_ADMIN' not in app.user.roles %}
        <div class="alert alert-danger" role="alert">
                Vous n'avez pas les droits d'accéder à cette page.
        </div>
    {% else %}
        <div class="MinWidthGeneral">
           <div class="creneauH4">
               <h4 id="h4Creneau">Creneaux Form</h4>
            </div>
           <div class="container">
                <div class="creneauxForm">
                    {{ form_start(form, {'attr': {'class': 'form'}}) }}
                    <div class="form-group">
                        {{ form_label(form.date, 'Date:', {'label_attr': {'class': ''}}) }}
                        {{ form_widget(form.date, {'attr': {'class': 'form-control', 'placeholder': 'Date ...'}}) }}
                    </div>
                    <div class="form-group">
                        <div class="creneauTypeLabel">
                            {{ form_label(form.permis, 'Type:', {'label_attr': {'class': ''}}) }}
                        </div>
                        {{ form_widget(form.permis, {'attr': {'class': 'form-control custom-style', 'placeholder': 'Date ...'}}) }}
                    </div>
                    <div class="form-group">
                        <div class="creneauFirst">
                            {{ form_label(form.user, 'Moniteur:', {'label_attr': {'class': ''}}) }}
                        </div>
                        {{ form_widget(form.user, {'attr': {'class': 'form-control'}}) }}
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-custom">Register</button>
                        {# <a href="{{ path('app_creneaux_index') }}" class="btn btn-secondary"><span>&#128412;</span>List</a> #}
                    </div>
                    {{ form_end(form) }}
                    </div>
                </div>
        </div>
         {% include 'footer.html.twig' %}
    {% endif %}
{% endblock %}

templates/creneaux/show.html.twig
{# {% extends 'base.html.twig' %}

{% block title %}Créneaux{% endblock %}

{% block body %}
{% if not app.user or 'ROLE_ADMIN' not in app.user.roles %}
        <div class="alert alert-danger" role="alert">
            Vous n'avez pas les droits d'accéder à cette page.
        </div>
{% else %}
   <div class="MinWidthGeneral" >
        <div class="table-responsive showCreneaux">
            <div class="creneauShowH4">
               <h4 id="h4Creneau">Show Détail</h4>
            </div>
            <table class="table">
                <tbody>
                    <tr>
                        <th scope="row">Id</th>
                        <td>{{ creneaux.id }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Date</th>
                        <td>{{ creneaux.date ? creneaux.date|date('Y-m-d H:i:s') : '' }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Moniteur</th>
                        <td>{{ creneaux.user.firstname }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Permis Type</th>
                        <td>{{ creneaux.permis.type }}</td>
                    </tr>
                    <tr>
                        <th scope="row">IsAvailable</th>
                        <td>{{ creneaux.isAvailable ? 'Yes' : 'No' }}</td>
                    </tr>
                </tbody>
            </table>
            <a class="btn btn-secondary" href="{{ path('app_creneaux_index') }}"><span>&#128412;</span>List</a>
                 <a class="btn btn-secondary" href="{{ path('app_creneaux_edit', {'id': creneaux.id}) }}">Edit</a>
        </div>
  </div>
 {{ include('creneaux/_delete_form.html.twig') }}
  {% include 'footer.html.twig' %}
 {% endif %}
{% endblock %} #}

templates/creneaux/updateCreneaux.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Creneaux{% endblock %}

{% block body %}
{% if not app.user or 'ROLE_ADMIN' not in app.user.roles %%}
        <div class="alert alert-danger" role="alert">
            Vous n'avez pas les droits d'accéder à cette page.
        </div>
{% else %}
    <div class="editGenerale">
        <h4>Modifier Creneaux</h4>

        {{ form_start(form, {'method': 'POST'}) }}

        <button type="submit" class="btnUpdate">Update</button>

        {{ form_end(form) }}

        <div class="deleteFormContainer">
            {{ include('creneaux/_delete_form.html.twig') }}
        </div>

        <a class="btnEdit" href="{{ path('app_creneaux_index') }}"><span>&#128412;</span>List</a>
    </div>
     {% include 'footer.html.twig' %}
    {% endif %}
{% endblock %}